# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d858ca03ff03647f582c9881140f4c83c9c7d574c92faae235c464d6a388e27c424893f5e37e2db4258a42e70dc8e49b209028c722e5021bd0532f26d7747d74

test:
  secret_key_base: 7c939d06b2f36c2d0c45338c3f2a3c45f75122721e9380ad997a2bdaf42858b7623a2af0fc441d8facc8826968b6382420c10b4976c131afd64c22eef464e672

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
